trigger:
- '*'

pool:
  name: 'Docker agent'

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.100'

steps:

- script: 'pwd'
  displayName: 'Show current directory'

- script: 'ls -l'
  displayName: 'List files'

- script: 'hostname'
  displayName: 'Show hostname'
